/** Do not edit. This file is generated by the command pnpm build:ts-modules **/

export const pink = {
  100: "#FCE7FB",
  200: "#F9D0F7",
  300: "#F5B8F3",
  400: "#F2A1EF",
  500: "#EF89EB",
  600: "#BF6EBC",
  700: "#8F528D",
  800: "#60375E",
  900: "#301B2F"
}

export const brown = {
  100: "#DED5CF",
  200: "#BDAC9F",
  300: "#9D826E",
  400: "#7C593E",
  500: "#5B2F0E",
  600: "#49260B",
  700: "#371C08",
  800: "#241306",
  900: "#120903"
}

export const tangelo = {
  100: "#FBE3D5",
  200: "#F8C7AC",
  300: "#F4A882",
  400: "#F18F59",
  500: "#ED732F",
  600: "#BE5C26",
  700: "#8E451C",
  800: "#5F2E13",
  900: "#2F1709"
}

export const orange = {
  100: "#FEE8CC",
  200: "#FFD889",
  300: "#FEC667",
  400: "#FFB02F",
  500: "#FA8A00",
  600: "#D76101",
  700: "#B04A00",
  800: "#7B3400",
  900: "#5A2400"
}

export const purple = {
  100: "#EEDDFD",
  200: "#DCBBFC",
  300: "#CB99FA",
  400: "#B977F9",
  500: "#A855F7",
  600: "#8644C6",
  700: "#653394",
  800: "#432263",
  900: "#221131"
}

export const yellow = {
  100: "#FFF5CC",
  200: "#FFEC99",
  300: "#FFE266",
  400: "#FFDE31",
  500: "#FFCF00",
  600: "#E7A200",
  700: "#9C6200",
  800: "#703E01",
  900: "#542A00"
}

export const blue = {
  100: "#E2F3FD",
  200: "#CBE5FE",
  300: "#89B4FA",
  400: "#629BFB",
  500: "#3B82F6",
  600: "#295EE0",
  700: "#1D4CBE",
  800: "#182F73",
  900: "#0C1A31"
}

export const green = {
  100: "#E1F2DF",
  200: "#C3E6BF",
  300: "#A5D99E",
  400: "#87CD7E",
  500: "#69C05E",
  600: "#549A4B",
  700: "#3F7338",
  800: "#2A4D26",
  900: "#152613"
}

export const red = {
  100: "#FCDADA",
  200: "#F9B4B4",
  300: "#F58F8F",
  400: "#F26969",
  500: "#EF4444",
  600: "#BF3636",
  700: "#8F2929",
  800: "#601B1B",
  900: "#300E0E"
}

export const gray = {
  0: "#FFFFFF",
  10: "#FAFAFA",
  20: "#F5F5F6",
  30: "#ECECEC",
  40: "#E0E0E0",
  50: "#C4C4C4",
  60: "#B5B5B6",
  70: "#A9A9AA",
  80: "#9B9B9C",
  90: "#8D8D8E",
  100: "#7E7E80",
  200: "#707071",
  300: "#626263",
  400: "#565657",
  500: "#484849",
  600: "#3C3C3D",
  700: "#2B2B2D",
  800: "#1D1D1F",
  900: "#111113"
}

export const pinkP3 = {
  100: "color(display-p3 0.974 0.909 0.979)",
  200: "color(display-p3 0.951 0.822 0.959)",
  300: "color(display-p3 0.924 0.731 0.939)",
  400: "color(display-p3 0.903 0.645 0.92)",
  500: "color(display-p3 0.883 0.557 0.901)",
  600: "color(display-p3 0.706 0.447 0.721)",
  700: "color(display-p3 0.528 0.333 0.54)",
  800: "color(display-p3 0.354 0.223 0.36)",
  900: "color(display-p3 0.177 0.11 0.18)"
}

export const brownP3 = {
  100: "color(display-p3 0.864 0.836 0.815)",
  200: "color(display-p3 0.73 0.677 0.63)",
  300: "color(display-p3 0.599 0.514 0.442)",
  400: "color(display-p3 0.466 0.355 0.259)",
  500: "color(display-p3 0.334 0.193 0.085)",
  600: "color(display-p3 0.268 0.156 0.067)",
  700: "color(display-p3 0.201 0.115 0.047)",
  800: "color(display-p3 0.132 0.078 0.031)",
  900: "color(display-p3 0.065 0.037 0.015)"
}

export const tangeloP3 = {
  100: "color(display-p3 0.968 0.894 0.842)",
  200: "color(display-p3 0.942 0.788 0.689)",
  300: "color(display-p3 0.913 0.672 0.534)",
  400: "color(display-p3 0.892 0.579 0.39)",
  500: "color(display-p3 0.869 0.478 0.255)",
  600: "color(display-p3 0.696 0.382 0.203)",
  700: "color(display-p3 0.52 0.286 0.15)",
  800: "color(display-p3 0.347 0.19 0.099)",
  900: "color(display-p3 0.171 0.095 0.046)"
}

export const orangeP3 = {
  100: "color(display-p3 0.981 0.913 0.812)",
  200: "color(display-p3 0.975 0.853 0.579)",
  300: "color(display-p3 0.962 0.785 0.463)",
  400: "color(display-p3 0.954 0.703 0.302)",
  500: "color(display-p3 0.922 0.563 0.205)",
  600: "color(display-p3 0.786 0.407 0.154)",
  700: "color(display-p3 0.642 0.314 0.114)",
  800: "color(display-p3 0.448 0.22 0.069)",
  900: "color(display-p3 0.327 0.154 0.039)"
}

export const purpleP3 = {
  100: "color(display-p3 0.922 0.869 0.983)",
  200: "color(display-p3 0.842 0.738 0.971)",
  300: "color(display-p3 0.766 0.608 0.956)",
  400: "color(display-p3 0.688 0.478 0.947)",
  500: "color(display-p3 0.617 0.351 0.936)",
  600: "color(display-p3 0.492 0.28 0.75)",
  700: "color(display-p3 0.37 0.21 0.56)",
  800: "color(display-p3 0.245 0.14 0.375)",
  900: "color(display-p3 0.124 0.07 0.185)"
}

export const yellowP3 = {
  100: "color(display-p3 0.993 0.962 0.817)",
  200: "color(display-p3 0.987 0.928 0.64)",
  300: "color(display-p3 0.981 0.89 0.477)",
  400: "color(display-p3 0.979 0.875 0.346)",
  500: "color(display-p3 0.97 0.819 0.277)",
  600: "color(display-p3 0.866 0.647 0.22)",
  700: "color(display-p3 0.579 0.395 0.126)",
  800: "color(display-p3 0.413 0.253 0.075)",
  900: "color(display-p3 0.308 0.173 0.041)"
}

export const blueP3 = {
  100: "color(display-p3 0.899 0.951 0.988)",
  200: "color(display-p3 0.815 0.895 0.986)",
  300: "color(display-p3 0.572 0.701 0.958)",
  400: "color(display-p3 0.435 0.602 0.957)",
  500: "color(display-p3 0.305 0.503 0.934)",
  600: "color(display-p3 0.215 0.364 0.847)",
  700: "color(display-p3 0.164 0.294 0.718)",
  800: "color(display-p3 0.115 0.182 0.434)",
  900: "color(display-p3 0.06 0.101 0.186)"
}

export const greenP3 = {
  100: "color(display-p3 0.895 0.947 0.88)",
  200: "color(display-p3 0.791 0.898 0.762)",
  300: "color(display-p3 0.689 0.845 0.641)",
  400: "color(display-p3 0.591 0.797 0.525)",
  500: "color(display-p3 0.495 0.745 0.413)",
  600: "color(display-p3 0.396 0.597 0.33)",
  700: "color(display-p3 0.296 0.446 0.246)",
  800: "color(display-p3 0.197 0.299 0.166)",
  900: "color(display-p3 0.097 0.147 0.082)"
}

export const redP3 = {
  100: "color(display-p3 0.966 0.86 0.857)",
  200: "color(display-p3 0.936 0.717 0.712)",
  300: "color(display-p3 0.906 0.58 0.571)",
  400: "color(display-p3 0.884 0.444 0.429)",
  500: "color(display-p3 0.865 0.322 0.297)",
  600: "color(display-p3 0.691 0.255 0.235)",
  700: "color(display-p3 0.517 0.192 0.177)",
  800: "color(display-p3 0.346 0.126 0.116)",
  900: "color(display-p3 0.172 0.063 0.059)"
}

export const grayP3 = {
  0: "color(display-p3 1 1 1)",
  10: "color(display-p3 0.98 0.98 0.98)",
  20: "color(display-p3 0.961 0.961 0.964)",
  30: "color(display-p3 0.925 0.925 0.925)",
  40: "color(display-p3 0.878 0.878 0.878)",
  50: "color(display-p3 0.769 0.769 0.769)",
  60: "color(display-p3 0.71 0.71 0.713)",
  70: "color(display-p3 0.663 0.663 0.666)",
  80: "color(display-p3 0.608 0.608 0.611)",
  90: "color(display-p3 0.553 0.553 0.557)",
  100: "color(display-p3 0.494 0.494 0.501)",
  200: "color(display-p3 0.439 0.439 0.443)",
  300: "color(display-p3 0.384 0.384 0.388)",
  400: "color(display-p3 0.337 0.337 0.341)",
  500: "color(display-p3 0.282 0.282 0.286)",
  600: "color(display-p3 0.235 0.235 0.239)",
  700: "color(display-p3 0.169 0.169 0.176)",
  800: "color(display-p3 0.114 0.114 0.121)",
  900: "color(display-p3 0.067 0.067 0.074)"
}
